apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyserver
  labels:
    app: pyserver
spec:
  replicas: 1 # quantidade de pods rodando
  selector:
    matchLabels:
      app: pyserver
  template:
    metadata:
      labels:
        app: "pyserver"
    spec:
      containers:
      - name: pyserver
        image: "davidbarenco/pyserver:v2"
        envFrom:
          - configMapRef:
             name: pyserver-env

        # Pegando variável por variável
        # env:
        #   - name: NAME
        #     valueFrom:
        #       configMapKeyRef:
        #         name: pyserver-env
        #         key: NAME
        #   - name: AGE
        #     valueFrom:
        #       configMapKeyRef:
        #         name: pyserver-env
        #         key: AGE
