apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyserver
  labels:
    app: pyserver
spec:
  replicas: 1 # quantidade de pods rodando
  selector:
    matchLabels:
      app: pyserver
  template:
    metadata:
      labels:
        app: "pyserver"
    spec:
      containers:
      - name: pyserver
        image: "davidbarenco/pyserver:v4"

        resources:
          # Mínimo: valor reservado do cluster1
          requests:
            # vCPU -> 1000m (milicores) 
            cpu: "0.3" # 300m
            memory: 64Mi
          limits:
            cpu: "0.3"
            memory: 128Mi

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 5 # checagem a cada segundos
          failureThreshold: 1 # quantas vezes vai dar errado pra reiniciar o pod
          timeoutSeconds: 1 # tempo limite da requisição de checagem
          successThreshold: 1 # quantas vezes testar pra dizer que a aplicação está live
          # initialDelaySeconds: 15 #começa a contar o check após esses segundos

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 3
          failureThreshold: 1
          # initialDelaySeconds: 10 # caso não use o startupProbe
          # timeoutSeconds: 1  # Valor default já é 1

        startupProbe:
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 3
          failureThreshold: 30
        env:
          - name: NAME
            value: "David"
          - name: AGE
            value: "35"

