apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyserver
  labels:
    app: pyserver
spec:
  replicas: 1 # quantidade de pods rodando
  selector:
    matchLabels:
      app: pyserver
  template:
    metadata:
      labels:
        app: "pyserver"
    spec:
      containers:
      - name: pyserver
        image: "davidbarenco/pyserver:v2"
        env:
          - name: NAME
            value: "David"
          - name: AGE
            value: "35"

