apiVersion: v1
kind: Pod
metadata:
  name: "pyserver"
  labels:
    app: "pyserver"
spec:
  containers:
  - name: pyserver
    image: "davidbarenco/pyserver:v1"
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    # ports:
    #   - containerPort: <Port>
